book/urls.py
from . import views
from django.urls import path


# urls for linking and redirecting

urlpatterns = [
    path('', views.BooksList.as_view(), name='home'),
    path('add_book/', views.add_book, name='add_book'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_category/', views.add_category, name='add_category'),
    path('<slug:slug>/', views.book_insight, name='book_insight'),
    path('<slug:slug>/edit_review/<int:review_id>', views.edit_review, name='edit_review'),  # noqa
    path('<slug:slug>/delete_review/<int:review_id>', views.delete_review, name='delete_review'),  # noqa
]

insight/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #path('',my_author,name='home'),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
    path("", include("book.urls"), name="book-urls"),
]

book/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from cloudinary.models import CloudinaryField
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Author(models.Model):
    """
    gives information about the author of the book
    many authors can have many books, but many books
    can only have one single author
    Shakespear wrote the Merchant of Venice, Romeo & Juliet and....
    George Orwel wrote Animal Farm, 1984 ...

    """
    fullname = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="add_authors")  # noqa
    author_image = CloudinaryField('image', default='placeholder')
    place_of_birth = models.CharField(max_length=200)
    date_of_birth = models.DateField()
    short_biography = models.TextField()
    created_on = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    # metaclass for default view on the admin page
    class Meta:
        ordering = ['-created_on', 'fullname']

    def __str__(self):
        return self.fullname


class Category(models.Model):
    """
    category will be used to specify the book genre whether it is politics,
    economics, sociology, thriller,
    """
    category_name = models.CharField(max_length=200, unique=True)
    category_description = models.TextField()

    class Meta:
        ordering = ['category_name']

    def __str__(self):
        return self.category_name


class Book(models.Model):
    """
    main class for showing books
    """
    title = models.CharField(max_length=200, unique=True)
    writer = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='book_author')  # noqa
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')  # noqa
    slug = models.SlugField(max_length=200, unique=True)
    cover_img = CloudinaryField('image', default='placeholder')
    short_description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    book_category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name="Genre")  # noqa
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on', 'title']

    def __str__(self):
        return self.title


class Review(models.Model):
    """
    for adding reviews on the selected book
    """
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="reviews")  # noqa
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter")  # noqa
    insight = models.TextField(blank=False)
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return self.insight


class Likes(models.Model):
    """
    see how many likes a book has got
    """
    likes = models.BooleanField(default=False)
    liked_book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='liked_book')  # noqa
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liker")  # noqa
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return str(self.id)


class Rating(models.Model):
    """
    see how many point out of 10 has a book got
    """
    rating = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(10.0)])  # noqa
    rated_book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="rated_book")  # noqa
    user_rated = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_rated')  # noqa
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return str(self.rating)

book/forms.py
from django import forms

from django.forms import ModelForm

from .models import Book, Author, Category, Likes, Review, Rating

# create a form for a book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'writer', 'cover_img', 'short_description', 'book_category')  # noqa


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('fullname', 'date_of_birth', 'author_image', 'place_of_birth', 'short_biography')  # noqa
        labels = {'fullname': 'Author fullname', 'date_of_birth': 'Date of Birth', 'author_image': 'Author Image', 'place_of_birth': 'Country of origin', 'short_biography': 'Short biography', }  # noqa
        widgets = {'date_of_birth': forms.DateInput(attrs={'type': 'text', 'placeholder': 'yyyy-mm-dd'}), }  # noqa


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('category_name', 'category_description')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('insight',)


class LikesForm(forms.ModelForm):
    class Meta:
        model = Likes
        fields = ('likes',)


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('rating',)
        labels = {'rating': 'Rating min(0.0) max(10.0)', }
        widgets = {
            'rating': forms.NumberInput(attrs={
                'min': '0.0',
                'max': '10.0',
                'step': '0.1',
            })
        }

book/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from .models import Author, Book, Category, Review, Likes, Rating
from .forms import BookForm, AuthorForm, CategoryForm, ReviewForm, LikesForm, RatingForm  # noqa
from django.db.models import Avg


# Create your views here.

class BooksList(generic.ListView):
    queryset = Book.objects.filter(approved=True)
    template_name = "book/index.html"
    paginate_by = 6


def transform_string(input_string):
    # Convert all characters to lowercase
    lowercase_string = input_string.lower()
    # Replace spaces with hyphens
    lower_case = lowercase_string.replace(' ', '-')
    # Replaces 's with -
    transform_string = lower_case.replace("'s", '-')
    return transform_string


def add_book(request):
    """
    Display Book  :model: book.book
    """
    submitted = False
    if request.method == "POST":
        bookForm = BookForm(request.POST, request.FILES)
        if bookForm.is_valid():
            print("Book form is valid")
            book = bookForm.save(commit=False)
            book.user = request.user
            book.slug = transform_string(book.title)
            book.save()
            submitted = True
            bookForm = BookForm()  # Reset the form after successful submission
            return HttpResponseRedirect('/add_book?submitted=True')
    else:
        bookForm = BookForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, "book/add_book.html", {'bookForm': bookForm, 'submitted': submitted})  # noqa


def add_author(request):
    """
    Adding author to the database
    """
    submitted = False
    if request.method == 'POST':
        authorForm = AuthorForm(request.POST, request.FILES)
        if authorForm.is_valid():
            author = authorForm.save(commit=False)
            author.user = request.user
            author.save()
            submitted = True
            authorForm = AuthorForm()  # Reset form after submission
            return HttpResponseRedirect('/add_author?submitted=True')
    else:
        authorForm = AuthorForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'book/add_author.html', {'authorForm': authorForm, 'submitted': submitted})  # noqa


def add_category(request):
    """
    Display Category  :model: book.Category
    """
    submitted = False
    if request.method == 'POST':
        categoryForm = CategoryForm(request.POST)
        if categoryForm.is_valid():
            categoryForm.save()
            submitted = True
            categoryForm = CategoryForm()
            return HttpResponseRedirect('/add_category?submitted=True')
    else:
        categoryForm = CategoryForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'book/add_category.html', {'categoryForm': categoryForm, 'submitted': submitted})  # noqa


def book_insight(request, slug):
    # book
    queryset = Book.objects.all()
    book = get_object_or_404(queryset, slug=slug)
    # author
    book_author = book.writer
    author_details = get_object_or_404(Author, fullname=book_author)
    # ratings
    book_rating_set = Rating.objects.filter(rated_book=book)
    user_has_rated = False

    for rate in book_rating_set:
        if rate.user_rated == request.user:
            user_has_rated = True
    # handling the rating mechanism
    if request.method == "POST":
        ratingForm = RatingForm(request.POST)
        if ratingForm.is_valid():
            one_rate = ratingForm.save(commit=False)
            one_rate.rated_book = book
            one_rate.user_rated = request.user
            one_rate.save()
            messages.add_message(request, messages.SUCCESS, f'{book.title} has been rated successfully')  # noqa
            return redirect(reverse('book_insight', kwargs={'slug': slug}))

    average_rating = book_rating_set.aggregate(Avg('rating'))['rating__avg']
    average_rating = 0 if average_rating is None else round(average_rating, 2)

    # reviews to show on a specific book
    reviews = book.reviews.all().order_by("-created_on")

    reviews_count = book.reviews.filter(approved=True).count()

    # handling the post request
    if request.method == 'POST':
        userReview = ReviewForm(request.POST)
        if userReview.is_valid():
            single_review = userReview.save(commit=False)
            single_review.book = book
            single_review.author = request.user
            single_review.save()
            userReview = ReviewForm()
            messages.add_message(request, messages.SUCCESS, f'Review for {book.title} submitted successfully and awaiting approval')  # noqa
            return redirect(reverse('book_insight', kwargs={'slug': slug}))
    # likes count
    likes = book.liked_book.count()
    all_likes = book.liked_book.all()
    user_liked_book = False
    for user_like in all_likes:
        if user_like.user_id == request.user:
            user_liked_book = True
    # handling likes for a book
    if request.method == "POST":
        likes_form = LikesForm(request.POST)
        if likes_form.is_valid():
            like = likes_form.save(commit=False)
            like.likes = True
            like.liked_book = book
            like.user_id = request.user
            like.save()
            messages.add_message(request, messages.SUCCESS, 'Like submitted successfully')  # noqa
            return redirect(reverse('book_insight', kwargs={'slug': slug}))

    # form for submitting a like
    likes_form = LikesForm()
    userReview = ReviewForm()
    ratingForm = RatingForm()
    return render(request, "book/book_insight.html",
                  {
                    'book': book,
                    'author_details': author_details,
                    'likes': likes,
                    'ratings': average_rating,
                    'reviews': reviews,
                    'reviews_count': reviews_count,
                    'userReview': userReview,
                    'likes_form': likes_form,
                    'all_likes': all_likes,
                    'user_liked_book': user_liked_book,
                    'ratingForm': ratingForm,
                    'user_has_rated': user_has_rated,
                    },)


def edit_review(request, slug, review_id):

    """
    edit the selected review
    """
    print(f"in the edit form {slug}  |  {review_id}",)
    if request.method == "POST":
        queryset = Book.objects.filter(approved=True)
        book = get_object_or_404(queryset, slug=slug)
        review = get_object_or_404(Review, pk=review_id)
        review_form = ReviewForm(data=request.POST, instance=review)

        if review_form.is_valid() and review.author == request.user:
            insight = review_form.save(commit=False)
            insight.book = book
            insight.approved = False
            insight.save()
            messages.add_message(request, messages.SUCCESS, 'Insight Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating insight!')  # noqa

    return HttpResponseRedirect(reverse('book_insight', args=[slug]))


def delete_review(request, slug, review_id):
    """
    delete a review from a book
    """
    review = get_object_or_404(Review, pk=review_id)
    if review.author == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, "Review deleted!")
    else:
        messages.add_message(request, messages.ERROR, "Only your own review ")

    return HttpResponseRedirect(reverse('book_insight', args=[slug]))

book/templates/book/add_author.html
{% extends "root.html" %}
{% load static %}
{% load i18n %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluide my-5 px4 text-center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 my-3 p-2">
      <h1 class="dark-blue">Tell us about your beloved writer</h1>
      <hr class="h-divider">
      <p class="dark-blue">Thoughts brought to life by authors make it worth reading about them</p>     
    </div>
  </div>
</div>

<!-- Here is the form -->
<div class="container my-5 px-4 text-center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 my-3 p-2">
      <h3 class="dark-blue">Adding Author Details</h3>
      <hr class="h-divider my-4">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-md-5 p-3 mb-2">
      <div class="p-1">
        {% if user.is_authenticated %}
        <!-- for to add a book-->
        <form action="" method=POST enctype="multipart/form-data" id="author-form">
          {% csrf_token %}
          {{ authorForm | crispy }}
          <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
          {% if submitted %}
          <span id="author-submitted" class="d-none" value="true"></span>
          {% else %}
          <span id="author-submitted" class="d-none" value="false"></span>
          {% endif %}
        </form>
        {% else %}
        <div class="container sign-in-up" >
          <div class="row justify-content-center">
            <h4>Sign in or Sign up to add your book</h4>
            <div class="col my-5">
              <h5>Already have an account then Sign in</h5>
              <br>
              <a href="{% url 'account_login' %}" class="btn btn-primary btn-lg">Sign In</a>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col my-5">
              <h5>Or Sign up for new account</h5>
              <br>
              <a href="{% url 'account_signup' %}" class="btn btn-primary btn-lg btn-add">Sign Up</a>
              
            </div>
          </div>
        </div>
        {% endif %}

      </div>
    </div>
    <div class="col-12 col-md-5 p-3 mb-2">
      <div class="section-img-container">
        <img src="{% static 'images/radu-marcusu-women-before-books.jpg' %}" class="scale" alt="">
      </div>
    </div>
  </div>
</div>
<!-- Adding Author Confirmation modal -->
 <!-- Confirmation Modal -->
 <div class="modal fade" id="authorConfirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title txt-dark-blue text-center" id="confirmationModalLabel">Successful Submission</h5>
      </div>
      <div class="modal-body">
        The author has been successfully saved to the database.
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block extras %}
    <script src="{% static 'js/books.js' %}"></script>
{% endblock %}

book/templates/book/add_book.html
{% extends "root.html" %}
{% load static %}
{% load i18n %}
{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluide my-5 px4 text-center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 my-3 p-2">
      <h1 class="dark-blue">Best friends when alone</h1>
      <hr class="h-divider">
      <p class="dark-blue">Reading a book is not a waste of time, but it is enlightening new ideas</p>     
    </div>
  </div>
</div>

<div class="container my-5 px-4 text-center justify-content-center custom-spacing">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 my-3 p-2">
      <h3 class="dark-blue">Adding a book</h3>
      <hr class="h-divider my-4">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-md-5 p-3 mb-2">
      <div class="p-1">
        {% if user.is_authenticated %}
        <!-- for to add a book-->
        <form action="" method=POST enctype="multipart/form-data" id="book-form">
          {% csrf_token %}
          {{ bookForm | crispy }}
          <button type="submit" value="submit" class="btn btn-primary">Submit</button>
          {% if submitted %}
           <span id="book-submitted" class="d-none" value="true"></span>
          {% else %}
          <span id="book-submitted" class="d-none" value="false"></span>
          {% endif %}
        </form>
        {% else %}
        <div class="container sign-in-up" >
          <div class="row justify-content-center">
            <h4>Sign in or Sign p to add your book</h4>
            <div class="col my-5">
              <h5>Already have an account then Sign in</h5>
              <br>
              <a href="{% url 'account_login' %}" class="btn btn-primary btn-lg">Sign In</a>
              
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col my-5">
              <h5>Or Sign up for new account</h5>
              <br>
              <a href="{% url 'account_signup' %}" class="btn btn-primary btn-lg btn-add">Sign Up</a>
              
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col-12 col-md-5 p-3 mb-2">
      <div class="section-img-container">
        <img src="{% static 'images/daria-nepriakhina-books-above-each-other.jpg' %}" class="scale" alt="">
      </div>
    </div>
  </div>
</div>

<!-- Adding Book Confirmation modal -->
 <!-- Confirmation Modal -->
<div class="modal fade" id="bookConfirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title txt-dark-blue text-center" id="confirmationModalLabel">Successful Submission</h5>
      </div>
      <div class="modal-body">
        The book has been successfully saved to the database.
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block extras %}
    <script src="{% static 'js/books.js' %}"></script>
{% endblock %}

book/templates/book/add_category.html
{% extends "root.html" %}
{% load static %}
{% load i18n %}
{% block content %}
{% load crispy_forms_tags %}


<div class="container-fluide my-5 px4 text-center">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 my-3 p-2">
      <h1 class="dark-blue">Book's Category ?</h1>
      <hr class="h-divider">
      <p class="dark-blue">Categories defines which field of book interest you most</p>     
    </div>
  </div>
</div>

<div class="container my-5 px-4 text-center ">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 my-3 p-2">
      <h3 class="dark-blue">Adding a Category</h3>
      <hr class="h-divider my-4">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-md-5 p-3 mb-2">
      <div class="p-1">
        
        {% if user.is_authenticated %}
        <!-- for to add a book-->
        <form action="" method=POST id="category-form">
          {% csrf_token %}
          {{ categoryForm | crispy }}
          <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
          {% if submitted %}
          <span id="category-submitted" class="d-none" value="true"></span>
         {% else %}
         <span id="category-submitted" class="d-none" value="false"></span>
         {% endif %}
        </form>
        {% else %}
        <div class="container sign-in-up">
          <div class="row justify-content-center">
            <h4>Sign in or Sign up to add your book</h4>
            <div class="col my-5">
              <h5>Already have an account then Sign in</h5>
              <br>
              <a href="{% url 'account_login' %}" class="btn btn-primary btn-lg">Sign In</a>
              
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col my-5">
              <h5>Or Sign up for new account</h5>
              <br>
              <a href="{% url 'account_signup' %}" class="btn btn-primary btn-lg btn-add">Sign Up</a>
              
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col-12 col-md-5 p-3 mb-2">
      <div class="section-img-container">
        <img src="{% static 'images/annelies-geneyn-book-on-grass.jpg' %}" class="scale" alt="">
      </div>
    </div>
  </div>
</div>
<!-- Adding Category Confirmation modal -->
 <!-- Confirmation Modal -->
 <div class="modal fade" id="categoryConfirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title txt-dark-blue text-center" id="confirmationModalLabel">Successful Submission</h5>
      </div>
      <div class="modal-body">
        The category has been successfully saved to the database.
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block extras %}
    <script src="{% static 'js/books.js' %}"></script>
{% endblock %}

book/templates/book/index.html
{% extends "root.html" %}
{% load static %}
{% block content %}
<!-- index and landing page starts here -->
<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
      aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/sylvia-yang-slid-1.jpg' %}" class="d-block w-100 slide-img"
        alt="first-slide">
      <div class="carousel-caption p-2">
        <h2>Add your beloved Author</h2>
        <p>Creative minds who drive always inspire generation to read more</p>
        <a href="{% url 'add_author' %}" class="btn btn-primary btn-lg" role="button">Add an Author</a>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/shiromani-slid-2.jpg' %}" class="d-block w-100 slide-img"
        alt="second-slide">
      <div class="carousel-caption p-2">
        <h2>What about reading categories?</h2>
        <p>Books'categories defines your section of interest to select a book</p>
        <a href="{% url 'add_category' %}" class="btn btn-primary btn-lg" role="button">Add a Category</a>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/shiromani-kant-slide-3.jpg' %}" class="d-block w-100 slide-img"
        alt="third-slide">
      <div class="carousel-caption p-2">
        <h2>Suggest a new book</h2>
        <p>Best guide to learn on you own pace</p>
        <a href="{% url 'add_book' %}" class="btn btn-primary btn-lg" role="button">Suggest a Book</a>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<!-- showing the books which are saved in the database -->
<div class="container">
  <div class="row">
    <div class="col my-3">
      <h1 class="book-gallery">Books Gallery</h1>
      <hr class="h-divider">
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for book in book_list %}
    <div class="col">
      <div class="card">
        {% if "placeholder" in book.cover_img.url %}
        <img src="{% static 'images/default.jpg' %}" class="card-img-top" width="125" height="450"
          alt="{{ book.title }}">
        {% else %}
        <img src="{{ book.cover_img.url }}" class="card-img-top" width="150" height="450" alt="{{ book.title }}">
        {% endif %}
        <div class="card-body">
          <h3 class="book-writer">{{ book.writer }}</h3>
          <hr class="h-divider">
          <h3 class="card-title">
            <a href="{% url 'book_insight' book.slug %}"class="book-link hvr-underline-from-center"> {{ book.title }}</a>
          </h3>
          <h4 class="card-category">{{ book.book_category }}</h4>
          <h6 class="book-user">added by: {{ book.user }} <span class="bar-seprator">|</span> on {{ book.created_on }}
          </h6>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation" class="my-2">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> PREV &laquo;</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}